# Problem Statement: You are given two strings s and t.

#String t is generated by random shuffling string s and then add one more letter at a random position.

#Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s, t):
    # We first do XOR on the characters of string s. After that we do XOR with t. The XOR operation will cancel all the elements that it has already seen and only the unique added element is left in ans variable.
        ans = 0

        for i in range(0, len(s)):
            ans = ans ^ ord(s[i])
        for i in range(0, len(t)):
            ans = ans ^ ord(t[i])
        
        return chr(ans)

s = "abcd"
t = "abcde"
print(Solution().findTheDifference(s, t))

s = ""
t = "y"
print(Solution().findTheDifference(s, t))